/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTC6 (number 111), HS_SWITCH_B_IN0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HS_SWITCH_B_IN0_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HS_SWITCH_B_IN0_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HS_SWITCH_B_IN0_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HS_SWITCH_B_IN0_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HS_SWITCH_B_IN0_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTC5 (number 110), HS_SWITCH_B_IN1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HS_SWITCH_B_IN1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HS_SWITCH_B_IN1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HS_SWITCH_B_IN1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HS_SWITCH_B_IN1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HS_SWITCH_B_IN1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
